# Generated by Django 2.0.6 on 2018-06-06 18:48

import aves.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mainImage', models.ImageField(upload_to=aves.models.directory_path_images)),
                ('mainAudio', models.FileField(blank=True, null=True, upload_to=aves.models.directory_path_images)),
                ('description', models.CharField(max_length=10000)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Familia')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('Ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.Ave')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Clase')),
            ],
        ),
        migrations.AddField(
            model_name='familia',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Orden'),
        ),
        migrations.AddField(
            model_name='especie',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Genero'),
        ),
        migrations.AddField(
            model_name='ave',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Clase'),
        ),
        migrations.AddField(
            model_name='ave',
            name='especie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Especie'),
        ),
        migrations.AddField(
            model_name='ave',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Familia'),
        ),
        migrations.AddField(
            model_name='ave',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Genero'),
        ),
        migrations.AddField(
            model_name='ave',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Orden'),
        ),
    ]
