# Generated by Django 2.0.2 on 2018-02-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField(blank=True, default=None)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Familia')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Clase')),
            ],
        ),
        migrations.CreateModel(
            name='Suborden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Orden')),
            ],
        ),
        migrations.AddField(
            model_name='familia',
            name='suborden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Suborden'),
        ),
        migrations.AddField(
            model_name='especie',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Genero'),
        ),
        migrations.AddField(
            model_name='ave',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Clase'),
        ),
        migrations.AddField(
            model_name='ave',
            name='familia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Familia'),
        ),
        migrations.AddField(
            model_name='ave',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Genero'),
        ),
        migrations.AddField(
            model_name='ave',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Orden'),
        ),
        migrations.AddField(
            model_name='ave',
            name='otherImages',
            field=models.ManyToManyField(to='aves.Image'),
        ),
        migrations.AddField(
            model_name='ave',
            name='suborden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='aves.Suborden'),
        ),
    ]
