# Generated by Django 2.0.3 on 2018-11-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aves.Ave')),
            ],
        ),
        migrations.CreateModel(
            name='FieldGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('aves', models.ManyToManyField(to='aves.Ave')),
            ],
        ),
    ]
