# Generated by Django 2.0.6 on 2018-06-05 08:22

import aves.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suborden',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='ave',
            name='suborden',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='suborden',
        ),
        migrations.AddField(
            model_name='ave',
            name='mainAudio',
            field=models.FileField(blank=True, null=True, upload_to=aves.models.directory_path_images),
        ),
        migrations.AddField(
            model_name='familia',
            name='orden',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='aves.Orden'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Suborden',
        ),
    ]
