# Generated by Django 2.0.3 on 2018-11-20 13:19

import aves.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aves', '0002_favorites_fieldguide'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldguide',
            name='mainImage',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=aves.models.directory_path_images_field_guide),
            preserve_default=False,
        ),
    ]
